### PR TITLE
loc stats added #5

### PR DESCRIPTION
**Pull request by marbetschar**
Enables querying loc inserted, deleted and the amount of files which are changed.

@franckverrot can you please have a look? Basically I would prefer if we could add a row per file which was modified, including the path. But I couldn't figure out how to do it. Maybe you have a hint?

Also there are no test cases yet, don't know how too ;)

### CODE REVIEW

**Comment by franckverrot** [comment]
Let's say you're targeting PG 10 (PG_VERSION=10).

There are some expected outputs in here: https://github.com/franckverrot/git_fdw/blob/master/tests/expected_outputs/10

And the main script is here: https://github.com/franckverrot/git_fdw/blob/master/tests/run.sql

Which is ran by this script: https://github.com/franckverrot/git_fdw/blob/master/tests/run.sh

So steps for implementing new features might be:

1.  Modify the expected output should fail your test
2.  Implement the code that you think should make it pass
3. Make it pass
4. Go to 1 for the next feature

Tell me if it helps.

**Comment by franckverrot** [comment]
Oh also, [your build](https://travis-ci.org/franckverrot/git_fdw/jobs/343631553) didn't pass because pulling PG 10 doesn't pull PG 10.0 anymore but PG 10.2.

```
KO, expected:
server_version_num,100000            <----------- this is PG 10.0
name,Franck Verrot;message,Initial commit
;sha1,4fc2faf9a0d051dc5c15a4821f1b790609b3074e
got:
server_version_num,100002            <----------- this is PG 10.2
name,Franck Verrot;message,Initial commit
;sha1,4fc2faf9a0d051dc5c15a4821f1b790609b3074e
```


Some solutions on top of my head:

1. Update the expected output to expect PG 10.2
or
1. Change the Dockerfile to pulling from the [Dockerhub](https://hub.docker.com/_/postgres/), which also defaults to 10.2, instead of `ubuntu:latest`

**Comment by marbetschar** [comment]
@franckverrot fixed.

**Comment by franckverrot** [comment]
Great.  So next part is about modifying the setup script so we can see the new fields, and modifying the expected outputs once again to check they’re showing up

**Comment by marbetschar** [comment]
obviously the returned values for `insertions`, `deletions` and `files_changed` are wrong. I assume this is due to the fact, that the initial commit does not have any parent and the algorithm now needs a parent to create the diff: https://travis-ci.org/franckverrot/git_fdw/jobs/343956518

That said, we probably need to switch gears and retrieve the child instead? Unfortunately [there seems not to be an easy way to achieve this](https://stackoverflow.com/questions/10539918/how-to-find-all-commits-having-a-particular-parent). Any ideas?

**Comment by marbetschar** [comment]
I probably found a solution using a combination of `git_revwalk_next` and `git_revwalk_push` to advance to child and return to parent afterwards. Crossing fingers ;)

**Comment by franckverrot** [comment]
Yup, seems like the way to go!

**Comment by marbetschar** [comment]
*grml* I don't really get it. Any idea why this code:
https://github.com/Mandelkind/git_fdw/blob/40d037978a31c226aeeece548d645b2161387c5d/git_fdw.c#L369-L388

Leads to an empty result set in the tests:
https://travis-ci.org/franckverrot/git_fdw/jobs/343975338

**Comment by marbetschar** [comment]
Initial approach was correct. Just needed to get the "empty-tree" to calculate the diff for the initial commit. For details see: https://stackoverflow.com/questions/40883798/how-to-get-git-diff-of-the-first-commit

**Comment by franckverrot** [comment]
Not sure without executing sorry.  Sometimes I'm a `puts`-debugger kind of developer, especially with FDWs where the code is running inside of PG itself... (I run my own PG though soooo, sometimes I can still debug stuff).  Try using [`elog`](https://www.postgresql.org/docs/10/static/error-message-reporting.html) if that helps :-)

**Comment by franckverrot** [comment]
Ah good find,  here's the link for those wondering what happened lol https://stackoverflow.com/questions/40883798/how-to-get-git-diff-of-the-first-commit

**Comment by franckverrot** [comment]
PR looks good.  I’ll review tonight and cut a release if things are still OK.  Thanks a bunch! 👌🏽

**Comment by franckverrot** [comment]
It's merged!  https://github.com/franckverrot/git_fdw/commit/88307aca45206d0df63aedbdd032ae7e8f249134

I rebased and also had to add a couple calls to `_free` on some objects that weren't collected after use.

**Comment by franckverrot** [comment]
I'm trying to push to pgxn but their ruby client is all messed up it seems.  Doesn't work on CI and doesn't install locally. I'll try to debug this soon but in the meantime, is using the repo directly an OK option?

**Comment by marbetschar** [comment]
Thank you very much! Using repo works as of now :)

**Pull request closed without merging**
